# Header
menu:
  Home: /
  About: /about/
  Projects: /projects/
  Archives: /archives/
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
  - category
  - tag
  - tagcloud
  - archive
  - recent_posts

# Miscellaneous
google_analytics: UA-647217-9
favicon: /favicon.png
twitter: cvrajeesh
google_plus: https://www.google.com/+RajeeshCV
fb_admins:
fb_app_id:
