name: Deploy website

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: "https://registry.npmjs.org"
          scope: "@clodui"

      - name: Install dependencies
        run: yarn install

      - name: Generate and deploy
        run: yarn run generate
        env:
          CLODUI_USERNAME: ${{ secrets.CLODUI_USERNAME }}
          CLODUI_PASSWORD: ${{ secrets.CLODUI_PASSWORD }}
          CLODUI_WEBSITE: ${{ secrets.CLODUI_WEBSITE }}

      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: clodui.log
          path: clodui.log
